name: gestao_restaurante
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.2
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  firebase_ui_auth: ^1.15.0
  get_it: any
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gutter: ^2.1.1
  flutter_localizations:
    sdk: flutter
  form_builder_image_picker: ^4.0.0
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  searchable_listview: ^2.14.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  mockito: ^5.4.4
  firebase_storage_mocks: ^0.7.0
  fake_cloud_firestore: ^3.0.1
dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/imgs/
