// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdkrliObWqhPMuGF1nPCtDnZOwBHeQ9sw',
    appId: '1:1086031755976:web:39aa47c5f20cdfa09bc3fd',
    messagingSenderId: '1086031755976',
    projectId: 'gestao-restaurante',
    authDomain: 'gestao-restaurante.firebaseapp.com',
    storageBucket: 'gestao-restaurante.appspot.com',
    measurementId: 'G-2LJ2F6QM9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6OVZ54zJDbhczKcYtzQhROtHJgJHWqjA',
    appId: '1:1086031755976:android:983bd4457b29ac279bc3fd',
    messagingSenderId: '1086031755976',
    projectId: 'gestao-restaurante',
    storageBucket: 'gestao-restaurante.appspot.com',
  );
}
