// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzI34gDA6_VOVPifIS-97MVMl4Uik9qQQ',
    appId: '1:423898073300:web:7aa795a169fe3d6c465341',
    messagingSenderId: '423898073300',
    projectId: 'perdidos-e-achados-4163a',
    authDomain: 'perdidos-e-achados-4163a.firebaseapp.com',
    storageBucket: 'perdidos-e-achados-4163a.appspot.com',
    measurementId: 'G-97G14J5C3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5kP5Wx2Dj0eyQehmt0-qqAKk4EqCaHK8',
    appId: '1:423898073300:android:9784479ba6269906465341',
    messagingSenderId: '423898073300',
    projectId: 'perdidos-e-achados-4163a',
    storageBucket: 'perdidos-e-achados-4163a.appspot.com',
  );

}